### ISSUE TITLE
Add an example of nomination by others, not just self-nominations

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/Elections#22]
We included an example of a self nomination. That makes sense, since it can come along with a vision statement about your values and goals for the foundation. But there's no reason not to allow other-nominations as well which is kind of more traditional. @zooko pointed out that by only having an example of self-nomination, this may only be appealing to people predisposed to self-aggrandizing (e.g. disproportionately males), let alone requiring a github account. I think a nice way to structure an other-nomination would be to include both:
- a forward/introduction by the nominator, who probably also submits the nomination via github
- include a vision statement from the nominee, which also serves to demonstrate that yes they accept the nomination

**Comment by amiller** [comment]
OK see #23 (i wish i githubbed better so there weren't two issues for this now, oh well)

**Comment by acityinohio** [comment]
Merged, thanks @amiller @zooko!
