### ISSUE TITLE
missing Community Governance Panel acceptance and rejection list

### ISSUE THREAD

**Issue by adrelanos** [ZcashFoundation/Elections#35]
> Please note: if you apply and are rejected, we are planning on making a public note of the rejection within this respository. This is to maximize transparency on the vetting process, given the limitation of the Foundation selecting members unilaterally. Please consider this before applying.

Where can I find the list of accepted and rejected Community Governance Panel Members?

**Comment by acityinohio** [comment]
https://github.com/ZcashFoundation/Elections/blob/master/2018-Q2/governance_panel.md
